# Generated by Django 2.1.4 on 2018-12-10 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_last_name', models.CharField(max_length=200)),
                ('author_full_name', models.CharField(max_length=200)),
                ('author_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_description', models.CharField(max_length=500)),
                ('owner_url', models.URLField()),
            ],
            options={
                'ordering': ('owner_name',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_summary', models.TextField()),
                ('text_original', models.TextField()),
                ('text_translation', models.TextField()),
                ('text_author', models.ManyToManyField(to='texts.Author')),
                ('text_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Owner')),
            ],
        ),
    ]
