# Generated by Django 2.1.4 on 2018-12-10 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='text',
            name='text_title',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
    ]
