# Generated by Django 2.1.4 on 2018-12-11 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20181210_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ('-text_publish',)},
        ),
        migrations.AddField(
            model_name='author',
            name='author_slug',
            field=models.SlugField(default='hello', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_slug',
            field=models.SlugField(default='hello', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='text_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='text',
            name='text_slug',
            field=models.SlugField(default='hello', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='text_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_texts', to='texts.Owner'),
        ),
    ]
