# Generated by Django 2.1.4 on 2018-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_auto_20181212_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(null=True, upload_to='author_images'),
        ),
        migrations.AddField(
            model_name='author',
            name='author_image_credit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_image',
            field=models.ImageField(null=True, upload_to='owner_images'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_image_credit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='text',
            name='text_image',
            field=models.ImageField(null=True, upload_to='text_images'),
        ),
        migrations.AddField(
            model_name='text',
            name='text_image_credit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
