# Generated by Django 2.1.4 on 2018-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_auto_20181213_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_original_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='text',
            name='text_original_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to='owner_images'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_image',
            field=models.ImageField(blank=True, null=True, upload_to='text_images'),
        ),
    ]
