# Generated by Django 2.1.4 on 2019-01-04 20:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_auto_20181213_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=100)),
                ('theme_slug', models.SlugField(max_length=100)),
                ('theme_image', models.ImageField(blank=True, null=True, upload_to='theme_images')),
                ('theme_image_credit', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='text_country',
            field=django_countries.fields.CountryField(default='NZ', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='text_themes',
            field=models.ManyToManyField(to='texts.Theme'),
        ),
    ]
