# Generated by Django 2.1.4 on 2019-01-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0010_auto_20190108_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='texts',
        ),
        migrations.AddField(
            model_name='text',
            name='themes',
            field=models.ManyToManyField(related_name='themes', to='texts.Theme'),
        ),
    ]
