# Generated by Django 2.1.4 on 2019-01-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_auto_20190109_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='country_images')),
                ('image_credit', models.CharField(blank=True, max_length=50)),
                ('featured', models.BooleanField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='text',
            name='country',
        ),
    ]
