# Generated by Django 2.1.4 on 2019-01-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0012_auto_20190115_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='country',
            field=models.ManyToManyField(to='texts.Country'),
        ),
    ]
